import os
os.environ["HF_HOME"] = "D:/hf_cache"  

import io
import torch
import librosa
import tempfile
import logging

from transformers import WhisperProcessor, WhisperForConditionalGeneration
from langchain_openai import ChatOpenAI
from os import getenv
from dotenv import load_dotenv

from config import MODEL_NAME, DEVICE, SAMPLING_RATE, STRUCTURE_LANGUAGE
from utils import MedicalCard
from prompt_render import render_system_prompt, render_user_prompt
from document_generator import generate_pdf, generate_docx
# from google import genai

load_dotenv()

logger = logging.getLogger("MainPipeline")
logger.setLevel(logging.INFO)

if not logger.handlers:
    handler = logging.StreamHandler()
    formatter = logging.Formatter(
        "[%(asctime)s] [%(levelname)s] %(name)s — %(message)s"
    )
    handler.setFormatter(formatter)
    logger.addHandler(handler)


class MainPipeline:

    def __init__(self):
        logger.info("Initializing MainPipeline")

        self.processor = WhisperProcessor.from_pretrained(
            MODEL_NAME,
            cache_dir="C:/Users/markiian_leshchyshyn/Documents/NULP/Diploma/code/train/model"
        )
        self.model = WhisperForConditionalGeneration.from_pretrained(
            MODEL_NAME,
            cache_dir="C:/Users/markiian_leshchyshyn/Documents/NULP/Diploma/code/train/model"
        ).to(DEVICE)

        logger.info("Whisper model and processor loaded")

        self.llm = ChatOpenAI(
            api_key=getenv("OPENROUTER_API_KEY"),
            base_url="https://openrouter.ai/api/v1",
            model="gpt-oss-20b",
            temperature=0.5
        ).with_structured_output(MedicalCard)

        logger.info("LLM client initialized")

        
    def _call_model_to_transcribe(self, audio_bytes: bytes) -> str:
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
            tmp.write(audio_bytes)
            tmp_path = tmp.name

        try:
            audio, sr = librosa.load(tmp_path, sr=SAMPLING_RATE)

            chunk_size = 15 * sr  
            texts = []

            logger.info("Audio duration: %.2f sec", len(audio) / sr)

            for i in range(0, len(audio), chunk_size):
                chunk = audio[i:i + chunk_size]

                inputs = self.processor(
                    chunk,
                    sampling_rate=sr,
                    return_tensors="pt"
                ).to(DEVICE)

                with torch.no_grad():
                    predicted_ids = self.model.generate(
                        inputs.input_features,
                        language="uk",
                        task="transcribe",
                    )

                text = self.processor.batch_decode(
                    predicted_ids,
                    skip_special_tokens=True
                )[0]

                texts.append(text)

            full_text = " ".join(texts)
            logger.info("Total transcription length: %d characters", len(full_text))

            return full_text

        finally:
            os.remove(tmp_path)


    def _call_model_to_structure(self, transcribed_text: str) -> MedicalCard:
        logger.info("Structuring transcription into MedicalCard")

        system_prompt = render_system_prompt(language=STRUCTURE_LANGUAGE)
        user_prompt = render_user_prompt(transcript=transcribed_text)

        try:
            result = self.llm.invoke([
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ])

            logger.info("MedicalCard successfully generated by LLM")
            return result

        except Exception as e:
            logger.exception("Error during MedicalCard structuring")
            raise

    def invoke_pipeline(self, audio_file: bytes, output_format: str):
        logger.info(f"Pipeline started | format={output_format}")

        try:
            transcribed_text = self._call_model_to_transcribe(audio_file)
            logger.info("Transcription: %s", transcribed_text)
            medical_card = self._call_model_to_structure(transcribed_text)

            fmt = output_format.lower()

            if fmt == "docx":
                logger.info("Generating DOCX document")
                return generate_docx(medical_card)

            elif fmt == "pdf":
                logger.info("Generating PDF document")
                return generate_pdf(medical_card)

            else:
                logger.error(f"Unsupported output format: {output_format}")
                raise ValueError(f"Unsupported output format: {output_format}")

        except ValueError as e:
            logger.error(f"Pipeline input error: {e}")
            raise RuntimeError(f"Pipeline input error: {e}")

        except Exception as e:
            logger.exception("Pipeline execution failed")
            raise RuntimeError(f"Pipeline execution failed: {e}")
