services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      BACKEND_BASE_URL: http://backend:8000
      MODEL_CACHE_DIR: /app/model
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    volumes:
      - ../model:/app/model
      - ../.env:/app/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    environment:
      BACKEND_BASE_URL: http://backend:8000
    depends_on:
      - backend
    ports:
      - "8501:8501"
